# Profile information
name: ProjArd
title: ProjArd - Projetos com Arduinos
description: > # this means to ignore newlines until "baseurl:"
  O site abriga vários projetos de arduinos prontos para tirar notas exelentes. No site voce encontra tutoriais bem detalhados para aprender a montar o projeto do "zero"
permalink: ':title/'
baseurl: "/projard" # the subpath of your site, e.g. /blog
url: "viniciusbozzi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your github

# Contact form
email: viniciusabozzi@gmail.com

# Comments
discus-identifier: vinciusbozzi

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
